# choose a basic image to start from
FROM node:17-alpine3.14

# install bash
RUN apk add --no-cache --upgrade bash

# a convention directory name to put the app in
RUN mkdir app

# copy the compiled js files into the container
COPY ./dist /app

# run with node the project root file (index.js) 
ENTRYPOINT [ "node","/app/index.js" ]