# choose a basic image to start from
FROM node:17-alpine3.14

# install bash
RUN apk update
RUN apk add --no-cache --upgrade bash git

# needed global packages for the project
RUN npm i -g typescript nodemon ts-node

# defines where to run the 'ENTRYPOINT' command from
WORKDIR /app

# copy the files into the image
# * later skafold will 'inject' code updates and nodemon will load them
COPY . .

# set the default main command of the container to run 'nodemon src/index.ts'
ENTRYPOINT ["nodemon" , "src/index.ts" ]
